events {
    worker_connections 4096;
}


http {
	upstream django { server 127.0.0.1:8000; }

	upstream django_teamquack { server 127.0.0.1:8010; }

	server {

		listen 80;
		server_name www.easternweb.ca easternweb.ca;		

		location / {
			autoindex on;
			root /root/nginx;
			auth_basic "Restricted";
			auth_basic_user_file /root/nginx/teamquack/.htpass;
		}
	}

	server {
		listen 80;
		server_name www.teamquack.ca teamquack.ca;
		return 301 https://$server_name$request_uri;
	}

	
	#redirect all tcp to https
	server {
		listen 80;
		server_name www.pdsquirrel.ca pdsquirrel.ca;
		return 301 https://$server_name$request_uri;
	}

	server {

		listen 443 ssl;
		#listen 80;
		server_name www.pdsquirrel.ca pdsquirrel.ca;
		client_max_body_size 2000m;

		# Old keys using lets encrypt
		#ssl_certificate /etc/letsencrypt/live/pdsquirrel.ca/fullchain.pem;
		#ssl_certificate_key /etc/letsencrypt/live/pdsquirrel.ca/privkey.pem;

		# Attempt one
		#ssl_certificate /etc/.cf/ssl_certificate.crt;
		#ssl_certificate_key /etc/.cf/server.csr;

		ssl_certificate /etc/ssl/pds/pdsquirrel.crt;
		ssl_certificate_key /etc/ssl/pds/privatekey.key;

		location / {
			uwsgi_pass django;
			include /root/nginx/pds/uwsgi_params;
			access_log /n.l;
			#auth_basic "Restricted";
			#auth_basic_user_file /root/nginx/pds/.htpass;
		}

		location /static {			
			alias /root/nginx/pds/pds_v3/static/;
			autoindex on;
		}
		location /attachments {
			alias /root/nginx/pds/attachments/;
			autoindex on;
		}

		location /audio_files {
			alias /root/nginx/pds/audio_files;
			autoindex on;
		}
	}
}
